

export const LOCATIONS = {
  CSL: "https://maps.app.goo.gl/bcMzASAyutmc1kc76",
  Beckman: "https://maps.app.goo.gl/ZyytaEnNzv4FfVgb8",
  HydrosystemsLab: "https://maps.app.goo.gl/vvi1mrBQGqWbJ4sV7",
  CoordinatedSciencesLab: "https://maps.app.goo.gl/anV3L5WEsAg5GYEg8",
  NCSA: "https://maps.app.goo.gl/GhxD2wNAraWHEkR47",
  NanotechLab: "https://maps.app.goo.gl/uEWpXUZRHcusdJo3A",
  Newmark: "https://maps.app.goo.gl/QJKip2z2syR4KYpJ9",
  SiebelCS: "https://maps.app.goo.gl/98VzDaMf5DdMC2yS8",
  KenneyGymAnnex: "https://maps.app.goo.gl/4kQcpAxo31mz1cvFA",
  DCL: "https://maps.app.goo.gl/PxQUKTLiMLYcMSv16",
  Grainger: "https://maps.app.goo.gl/TAApkdbXnZxZwPQZ9",
  GraingerDock: "",
  ESPL: "https://maps.app.goo.gl/F2fRbv9NUGFpDQaN9",
  Talbot: "https://maps.app.goo.gl/hFqG7LjBDHUE93p4A",
  MEL: "https://maps.app.goo.gl/7yEhGXZqupWac6m48",
  MSEB: "https://maps.app.goo.gl/1qM1sFCmjcwQZ9vC6",
  TransportationBuilding: "https://maps.app.goo.gl/1bm1cL93Rqffz8Jy9",
  MRL: "https://maps.app.goo.gl/dwxWFixKYoebaE9Z8",
  IlliniUnion: "https://maps.app.goo.gl/okF8HkjEdgSzdz9e7",
  NHB: "https://maps.app.goo.gl/RjkJ2exzC1Q88qpS7",
  EHall: "https://maps.app.goo.gl/EGdQyRu1WbrpWjAeA",
  StockPavillion: "https://maps.app.goo.gl/cyWWDp957gstt9sq5",
  Observatory: "https://maps.app.goo.gl/ahJ4abSKegeqRJBm6",
  Everitt: "https://maps.app.goo.gl/TRc9W1BsL5RWhn1n7",
  BardeenQuad: "https://maps.app.goo.gl/fFfYoGfgogKjQWeK8",
  CIF: "https://maps.app.goo.gl/1QBXd3aDN5wiYnzm7",
  GrazianoPlaza: "https://maps.app.goo.gl/KQNFQZhEeD3yCNvK9",
  SidneyLu: "https://maps.app.goo.gl/GsqZ6399qMoebvFn6",
  MEB: "https://maps.app.goo.gl/ZSVuDXNVNBu1X3oR6",
  Loomis: "https://maps.app.goo.gl/2raT3utFA19iiEi77",
  ECEB: "https://maps.app.goo.gl/KPMcpcN28SS1KxkeA",
}
