-- AlterSequence
ALTER SEQUENCE "Slot_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "WaitListed" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "VolunteerId" INT4 NOT NULL,
    "slotId" INT4 NOT NULL,

    CONSTRAINT "WaitListed_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "WaitListed" ADD CONSTRAINT "WaitListed_slotId_fkey" FOREIGN KEY ("slotId") REFERENCES "Slot"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
