import { Fragment } from "react";
import Content from "@/content";
import Head from "next/head";
import Bubble from "@/bubble";
import Button from "@/button";
import SponsorCard from "@/sponsor-card";
import Event from "@/event"

export default function EventsList() {
  return (
    <Content title="Special Events">
        <div className="lg:col-span-3 mb-10">
            <div className="font-montserrat col-span-5">
                {/* <Event color="#edd4d3" description="Join us for our keynote speaker to kick off EOH 2023! Our keynote speaker this year is Todd Little who is the chief architect at Oracle and an Alumni of The Grainger College of Engineering. With more than 40 years of software architecture and development experience, he has also received two patents for methods allowing design patterns in a UML modeling tool to control the generation of software artifacts." title="Keynote Speaker" location="CIF 0027" dateTime="Friday 6-7 pm" icon="assets/icons/keynote.png"/>
                <Event color="#e8c9c8" description="Just as dark falls, visit the Bardeen Quad to see an electrifying display of light and sound." title="Tesla Coil" location="Bardeen Quad" dateTime="Friday 8 pm" icon="assets/icons/tesla.png"/>
                <Event color="#debcba" description="Build-a-Blinkie is an organization dedicated to the teaching of STEM. We are teaching people to solder one blinkie at a time. Come check out this interactive activity and take home your own soldered blinkie! The custom EOH Blinkies are sponsored by the Dyson Foundation, stop by their booth next to Build-a-Blinkie to learn more about their engineering innovation!" title="Build-A-Blinkie" location="CIF 0035" dateTime="Friday 1-4 pm, Saturday 9-4 pm" icon="assets/icons/blinkie.png"/>
                <Event color="#dbb1af" description="On Friday, March 31 f rom 1:00pm-2:00pm CT,  join Dyson engineers for an info session and Q+A on their James Dyson Award. During the session, you will hear an overview of Dyson’s design process and tips for what makes a winning entry to their annual engineering competition, the James Dyson Award." title="Dyson Tech Talk and James Dyson Award Info-Session" location="DCL 1320" dateTime="Friday 1-2 pm"/>
                <Event color="#d4a7a5" description="This EOH showcase track is for vehicles built and designed by engineering student teams for collegiate competitions: two formula racecars (one electric powered and the other gas), a Baja off-road ATV, a 3-wheeled super-mileage vehicle, an electric commuter concept car, a tractor-pull, and a solar powered vehicle. This is a great opportunity for action pictures and for the public to talk to team members between demonstration events." title="ESPL Demo" location="Grainger Loading Dock" dateTime="Friday and Saturday: 10 am, 11 am, 1 pm, 2 pm. Additional demo Friday 3 pm" icon="assets/icons/espldemo.png"/>
                <Event color="#c99997" description="Simulation training is revolutionizing medical education today. Come learn medical techniques in a low-risk environment with virtual reality, manikins, and more, it’s as close to reality as possible without affecting a human’s health and safety." title="Jump Simulation Center Demo" location="Everitt Basement Carle Jump Lab" dateTime="Friday and Saturday: 9-5 pm" icon="assets/icons/jumplab.png"/>
                <Event color="#c7918f" description="We make Robots In KIMLAB (Kinetic Intelligent Machine LAB)! KIMLAB members will showcase the latest robots developed and demonstrate how these robots can be used for various tasks. Don’t miss out on this one-of-a-kind experience!" title="KIMLAB Robot Demo" location="LUMEB 1100: near Starbucks" dateTime="Friday and Saturday: 10:30 am, 11:30 am, 12:30 pm, 1:30 pm" icon="assets/icons/kimlab.png"/>
                <Event color="#c48886" description="LabEscape: Quantum Salvation. World-renowned scientist Prof. S. desperately needs your help. A terrible virus could be the end of life as we know it. Quantum tech is humanity’s only hope...We recommend teams of five to seven people for this science-based escape room; we will help you by adding other solo agents until the roster is complete, with a minimum of four people required. If there are fewer than four agents by mission time, we may need to cancel that run, so your best bet is to assemble a team now!" title="LabEscape" location="DCL 1262" dateTime="Sign up at this link: " link="my.physics.illinois.edu/extranet/labescape/eoh2023/" icon="assets/icons/labescape.png"/>
                <Event color="#c78683" description="Feeling inspired f rom checking out student exhbits? Now it’s your turn to become the engineer! Come check out our design lab where you’ll be able to let your imagination run wild! Recommended for ages 10 and under!" title="LEGO Design Lab" location="CIF 2036" dateTime="Friday and Saturday: 9:30-5 pm" icon="assets/icons/lego.png"/>
                <Event color="#c27d7a" description="We are excited to share with you the engineering majors that make up our Grainger College of Engineering. Deciding your college major is an important step towards your future goals and the Majors Fair is a great opportunity for you to explore and learn about the opportunities that lie within every major and field of engineering study offered! Stop by to talk to current students about their experiences and advice about choosing the perfect path for you!" title="Majors Fair" location="CIF 2039" dateTime="Friday and Saturday: 12-4 pm" icon="assets/icons/majors.png"/>
                <Event color="#bf7471" description="See visualizations of galaxies, tornadoes, molecular structures, and more created by NCSA’s Advanced Visualization Lab. Many of these visualizations were created for documentary films, IMAX, and museums and will be shown in 3D." title="NCSA" location="NCSA 1005" dateTime="Friday 9-4 pm" icon="assets/icons/ncsa.png"/>
                <Event color="#bd6b68" description="Do you like explosions? Ever thought about using a banana as a hammer? Have you wondered why things are the way they are? Then come watch Physics Van! We are a traveling magic science show that wants to make science fun and relatable. Join us for an hour long show, or stop by at any time and enjoy our liquid nitrogen booth. It’s the coolest demos you’ll ever see (literally)." title="Physics Van" location="Loomis 141" dateTime="Friday and Saturday: 10 am, 12 pm, 2 pm" icon="assets/icons/physicsvan.png"/>
                <Event color="#ba625f" description="Want to get a feel for life on campus as a Grainger engineering student? Come listen to student’s talk about their first hand experience. They will be discussing everything f rom favorite classes to their favorite way to destress on campus!" title="Prospective Student Info-Session & Panel" location="CIF 2018" dateTime="Friday 9:30-10:30 am, Saturday 10-10:30 am" icon="assets/icons/prospectivestu.png"/>
                <Event color="#b55855" description="UIUC’s Rube Goldberg Society’s large sci-fi themed Rube Goldberg machine tells the story of some f ruity aliens. Taking inspiration f rom the popular Rube Goldberg comics, the society creates one new giant machine of chain reactions every year to complete one simple task. Watch their machine run every half hour." title="Rube Goldberg" location="MechE 1047" dateTime="Friday and Saturday: 10-3:30 pm every 30 min" icon="assets/icons/rubegoldberg.png"/>
                <Event color="#b55350" description="The Startup Showcase is dedicated to celebrating student entrepreneurs! Come see what our inventive Illinois students have been working on at their booths and experience demos, giveaways, and much more!" title="Startup Showcase" location="CIF 3039 Startup Booths" dateTime="Friday 10-3 pm, Saturday 11-4 pm" />
                <Event color="#b34c49" description="Listen in on advice f rom current college students on what activities helped them discover their passion and any tips they have for prospective students!" title="What I Wish I Knew When I Was In High School Panel" location="CIF 2018" dateTime="Friday and Saturday: 11-11:30 am" icon="assets/icons/whatiwishhs.png"/>
                <Event color="#b04643" description="Stop by Talbot Lab to learn about flow with the Women in Aerospace! WIA graduate students are doing demonstrations of the Aerospace Department wind tunnels with a moving airfoil lab! These wind tunnels are great examples of how we can model and research airflows for a variety of industries, such as automotive and industrial uses." title="Wind Tunnel Demos with WIA" location="Talbot Library" dateTime="Friday and Saturday: 9-5 pm"/>
                <Event color="#b0413e" description="Check out some of our women engineering students and professors talk about their experiences in their respective fields!" title="Women In Engineering Panel" location="CIF 2018" dateTime="Friday and Saturday: 1-1:30 pm" icon="assets/icons/wiepanel.png"/>
                <Event color="#a83936" description="Please join us for awards to wrap up EOH 2023! Location will be announced later." title="EOH 2023 Awards" location="CIF Monumental Steps" dateTime="Saturday 4-5 pm"/> */}

                <Event color="#edd4d3" description="Join us for our keynote speaker to kick off EOH 2023! Our keynote speaker this year is Todd Little who is the chief architect at Oracle and an Alumni of The Grainger College of Engineering. With more than 40 years of software architecture and development experience, he has also received two patents for methods allowing design patterns in a UML modeling tool to control the generation of software artifacts." title="Keynote Speaker" location="CIF 0027" dateTime="Friday 6-7 pm"/>
                <Event color="#e8c9c8" description="Just as dark falls, visit the Bardeen Quad to see an electrifying display of light and sound." title="Tesla Coil" location="Bardeen Quad" dateTime="Friday 8 pm"/>
                <Event color="#debcba" description="Build-a-Blinkie is an organization dedicated to the teaching of STEM. We are teaching people to solder one blinkie at a time. Come check out this interactive activity and take home your own soldered blinkie! The custom EOH Blinkies are sponsored by the Dyson Foundation, stop by their booth next to Build-a-Blinkie to learn more about their engineering innovation!" title="Build-A-Blinkie" location="CIF 0035" dateTime="Friday 1-4 pm, Saturday 9-4 pm"/>
                <Event color="#dbb1af" description="On Friday, March 31 f rom 1:00pm-2:00pm CT,  join Dyson engineers for an info session and Q+A on their James Dyson Award. During the session, you will hear an overview of Dyson’s design process and tips for what makes a winning entry to their annual engineering competition, the James Dyson Award." title="Dyson Tech Talk and James Dyson Award Info-Session" location="DCL 1320" dateTime="Friday 1-2 pm"/>
                <Event color="#d4a7a5" description="This EOH showcase track is for vehicles built and designed by engineering student teams for collegiate competitions: two formula racecars (one electric powered and the other gas), a Baja off-road ATV, a 3-wheeled super-mileage vehicle, an electric commuter concept car, a tractor-pull, and a solar powered vehicle. This is a great opportunity for action pictures and for the public to talk to team members between demonstration events." title="ESPL Demo" location="Grainger Loading Dock" dateTime="Friday and Saturday: 10 am, 11 am, 1 pm, 2 pm. Additional demo Friday 3 pm"/>
                <Event color="#c99997" description="Simulation training is revolutionizing medical education today. Come learn medical techniques in a low-risk environment with virtual reality, manikins, and more, it’s as close to reality as possible without affecting a human’s health and safety." title="Jump Simulation Center Demo" location="Everitt Basement Carle Jump Lab" dateTime="Friday and Saturday: 9-5 pm"/>
                <Event color="#c7918f" description="We make Robots In KIMLAB (Kinetic Intelligent Machine LAB)! KIMLAB members will showcase the latest robots developed and demonstrate how these robots can be used for various tasks. Don’t miss out on this one-of-a-kind experience!" title="KIMLAB Robot Demo" location="LUMEB 1100: near Starbucks" dateTime="Friday and Saturday: 10-11 am, 2-3pm"/>
                <Event color="#c48886" description="LabEscape: Quantum Salvation. World-renowned scientist Prof. S. desperately needs your help. A terrible virus could be the end of life as we know it. Quantum tech is humanity’s only hope...We recommend teams of five to seven people for this science-based escape room; we will help you by adding other solo agents until the roster is complete, with a minimum of four people required. If there are fewer than four agents by mission time, we may need to cancel that run, so your best bet is to assemble a team now!" title="LabEscape" location="DCL 1262" dateTime="Sign up at this link: " link="my.physics.illinois.edu/extranet/labescape/eoh2023/"/>
                <Event color="#c78683" description="Feeling inspired f rom checking out student exhbits? Now it’s your turn to become the engineer! Come check out our design lab where you’ll be able to let your imagination run wild! Recommended for ages 10 and under!" title="LEGO Design Lab" location="CIF 2036" dateTime="Friday and Saturday: 9:30-5 pm"/>
                <Event color="#c27d7a" description="We are excited to share with you the engineering majors that make up our Grainger College of Engineering. Deciding your college major is an important step towards your future goals and the Majors Fair is a great opportunity for you to explore and learn about the opportunities that lie within every major and field of engineering study offered! Stop by to talk to current students about their experiences and advice about choosing the perfect path for you!" title="Majors Fair" location="CIF 2039" dateTime="Friday and Saturday: 12-4 pm"/>
                <Event color="#bf7471" description="See visualizations of galaxies, tornadoes, molecular structures, and more created by NCSA’s Advanced Visualization Lab. Many of these visualizations were created for documentary films, IMAX, and museums and will be shown in 3D." title="NCSA" location="NCSA 1005" dateTime="Friday 9-4 pm"/>
                <Event color="#bd6b68" description="Do you like explosions? Ever thought about using a banana as a hammer? Have you wondered why things are the way they are? Then come watch Physics Van! We are a traveling magic science show that wants to make science fun and relatable. Join us for an hour long show, or stop by at any time and enjoy our liquid nitrogen booth. It’s the coolest demos you’ll ever see (literally)." title="Physics Van" location="Loomis 141" dateTime="Friday and Saturday: 10 am, 12 pm, 2 pm"/>
                <Event color="#ba625f" description="Want to get a feel for life on campus as a Grainger engineering student? Come listen to student’s talk about their first hand experience. They will be discussing everything f rom favorite classes to their favorite way to destress on campus!" title="Prospective Student Info-Session & Panel" location="CIF 2018" dateTime="Friday 9:30-10:30 am, Saturday 10-10:30 am"/>
                <Event color="#b55855" description="UIUC’s Rube Goldberg Society’s large sci-fi themed Rube Goldberg machine tells the story of some f ruity aliens. Taking inspiration f rom the popular Rube Goldberg comics, the society creates one new giant machine of chain reactions every year to complete one simple task. Watch their machine run every half hour." title="Rube Goldberg" location="MechE 1047" dateTime="Friday and Saturday: 10-3:30 pm every 30 min"/>
                <Event color="#b55350" description="The Startup Showcase is dedicated to celebrating student entrepreneurs! Come see what our inventive Illinois students have been working on at their booths and experience demos, giveaways, and much more!" title="Startup Showcase" location="CIF 3039 Startup Booths" dateTime="Friday 10-3 pm, Saturday 11-4 pm"/>
                <Event color="#b34c49" description="Listen in on advice f rom current college students on what activities helped them discover their passion and any tips they have for prospective students!" title="What I Wish I Knew When I Was In High School Panel" location="CIF 2018" dateTime="Friday and Saturday: 11-11:30 am"/>
                <Event color="#b04643" description="Stop by Talbot Lab to learn about flow with the Women in Aerospace! WIA graduate students are doing demonstrations of the Aerospace Department wind tunnels with a moving airfoil lab! These wind tunnels are great examples of how we can model and research airflows for a variety of industries, such as automotive and industrial uses." title="Wind Tunnel Demos with WIA" location="Talbot Library" dateTime="Friday and Saturday: 9-5 pm"/>
                <Event color="#b0413e" description="Check out some of our women engineering students and professors talk about their experiences in their respective fields!" title="Women In Engineering Panel" location="CIF 2018" dateTime="Friday and Saturday: 1-1:30 pm"/>
                <Event color="#a83936" description="Please join us for awards to wrap up EOH 2023! Location will be announced later." title="EOH 2023 Awards" location="CIF Monumental Steps" dateTime="Saturday 4-5 pm"/>
            </div>
        </div>
    </Content>
  );
}
